#pragma once

// This file is automatically generated and should not be modified manually.

#include <cstddef>
#include <cstdint>

namespace lzx {

namespace project_version {

constexpr const char *git_tag = "0.1.7";
constexpr const char *git_hash = "g7db71a3";
constexpr unsigned long git_commits = 123;
constexpr unsigned long major = 0;
constexpr unsigned long minor = 1;
constexpr unsigned long patch = 7;

} // namespace project_version

} // namespace lzx
