#pragma once

// This file is automatically generated and should not be modified manually.

#include <cstddef>
#include <cstdint>

namespace lzx {

namespace videomancer_sdk_version {

constexpr const char *git_tag = "0.1.0";
constexpr const char *git_hash = "gd8a5be0";
constexpr unsigned long git_commits = 1;
constexpr unsigned long major = 0;
constexpr unsigned long minor = 1;
constexpr unsigned long patch = 0;

} // namespace videomancer_sdk_version

} // namespace lzx
