#!/usr/bin/env python3
# Videomancer SDK - Core Config Package Generator
# Copyright (C) 2025 LZX Industries LLC
# SPDX-License-Identifier: GPL-3.0-only
#
# Generates a VHDL core_config_pkg with per-build C_HD_CLOCK_DIVISOR.
# Used by the Makefile when HD_CLOCK_DIVISOR > 1 to override the static
# config package with a generated one containing the correct divisor value.

"""Generate core_config_pkg.vhd with configurable HD clock divisor."""

import argparse
import sys
from pathlib import Path

# Map config name to boolean flag values
CONFIG_MAP = {
    "sd_analog":     {"sd": True,  "hd": False, "analog": True,  "hdmi": False, "dual": False, "standalone": False},
    "sd_hdmi":       {"sd": True,  "hd": False, "analog": False, "hdmi": True,  "dual": False, "standalone": False},
    "sd_dual":       {"sd": True,  "hd": False, "analog": True,  "hdmi": True,  "dual": True,  "standalone": False},
    "sd_standalone": {"sd": True,  "hd": False, "analog": True,  "hdmi": False, "dual": False, "standalone": True},
    "hd_analog":     {"sd": False, "hd": True,  "analog": True,  "hdmi": False, "dual": False, "standalone": False},
    "hd_hdmi":       {"sd": False, "hd": True,  "analog": False, "hdmi": True,  "dual": False, "standalone": False},
    "hd_dual":       {"sd": False, "hd": True,  "analog": True,  "hdmi": True,  "dual": True,  "standalone": False},
    "hd_standalone": {"sd": False, "hd": True,  "analog": True,  "hdmi": False, "dual": False, "standalone": True},
}

TEMPLATE = """\
-- Videomancer SDK - Generated Core Configuration Package
-- Copyright (C) 2025 LZX Industries LLC
-- SPDX-License-Identifier: GPL-3.0-only
--
-- AUTO-GENERATED by gen_core_config.py — DO NOT EDIT
-- Config: {config}, HD Clock Divisor: {divisor}

library ieee;
use ieee.std_logic_1164.all;

package core_config_pkg is
  constant C_ENABLE_ANALOG     : boolean := {analog};
  constant C_ENABLE_HDMI       : boolean := {hdmi};
  constant C_ENABLE_DUAL       : boolean := {dual};
  constant C_ENABLE_STANDALONE : boolean := {standalone};
  constant C_ENABLE_SD         : boolean := {sd};
  constant C_ENABLE_HD         : boolean := {hd};
  constant C_HD_CLOCK_DIVISOR  : integer := {divisor};
end package core_config_pkg;
"""


def bool_vhdl(val: bool) -> str:
    return "true" if val else "false"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate core_config_pkg.vhd with HD clock divisor"
    )
    parser.add_argument(
        "--config",
        required=True,
        choices=sorted(CONFIG_MAP.keys()),
        help="Video configuration name",
    )
    parser.add_argument(
        "--hd-clock-divisor",
        type=int,
        default=1,
        choices=[1, 2, 4],
        help="HD clock divisor (1=full speed, 2=half, 4=quarter)",
    )
    parser.add_argument(
        "--output",
        required=True,
        type=Path,
        help="Output VHDL file path",
    )
    args = parser.parse_args()

    flags = CONFIG_MAP[args.config]

    content = TEMPLATE.format(
        config=args.config,
        divisor=args.hd_clock_divisor,
        analog=bool_vhdl(flags["analog"]),
        hdmi=bool_vhdl(flags["hdmi"]),
        dual=bool_vhdl(flags["dual"]),
        standalone=bool_vhdl(flags["standalone"]),
        sd=bool_vhdl(flags["sd"]),
        hd=bool_vhdl(flags["hd"]),
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content)
    return 0


if __name__ == "__main__":
    sys.exit(main())
