-- Videomancer SDK - VUnit Testbench for glitch_free_clock_mux
-- Copyright (C) 2025 LZX Industries LLC
-- SPDX-License-Identifier: GPL-3.0-only
--
-- Tests:
--   1.  default_select_a -- with i_sel='0' the output runs at i_clk_a's frequency
--   2.  default_select_b -- with i_sel='1' the output runs at i_clk_b's frequency
--   3.  switch_a_to_b -- toggling i_sel cleanly retargets the output to i_clk_b
--   4.  switch_b_to_a -- and back again
--   5.  no_short_intervals -- across many sel toggles, every observed
--                             edge-to-edge interval on the output is >=
--                             the faster source's half-period (i.e. no
--                             runt pulses generated by the gate switch-over)
--   6.  no_double_speed -- across many sel toggles, the output edge rate
--                          never exceeds the faster source's rate (rules
--                          out simultaneous-leak failure mode)
--
-- The sources are 13.5 MHz (clk_a) and 27 MHz (clk_b), the SD-standalone
-- pixel clocks selected by `timing_register_id(2)` in the SD standalone core.

library ieee;
use ieee.std_logic_1164.all;

library vunit_lib;
context vunit_lib.vunit_context;

library rtl_lib;

entity tb_glitch_free_clock_mux is
  generic (runner_cfg : string);
end entity;

architecture tb of tb_glitch_free_clock_mux is

  constant C_PER_A : time := 74074 ps;  -- 13.5 MHz
  constant C_PER_B : time := 37037 ps;  -- 27 MHz

  signal clk_a : std_logic := '0';
  signal clk_b : std_logic := '0';
  signal sel   : std_logic := '0';
  signal o_clk : std_logic;
  signal stop  : std_logic := '0';

begin

  clk_a <= not clk_a after C_PER_A / 2 when stop = '0' else unaffected;
  clk_b <= not clk_b after C_PER_B / 2 when stop = '0' else unaffected;

  dut : entity rtl_lib.glitch_free_clock_mux
    port map (
      i_clk_a => clk_a,
      i_clk_b => clk_b,
      i_sel   => sel,
      o_clk   => o_clk
    );

  main : process

    -- Count rising edges of o_clk over `window` and verify the count is
    -- close to (window / src_period).
    procedure check_freq(constant src_period : time;
                         constant src_label  : string;
                         constant window     : time) is
      variable n_edges  : integer := 0;
      variable expected : integer;
      variable t_start  : time;
    begin
      wait until rising_edge(o_clk);
      t_start := now;
      while now - t_start < window loop
        wait on o_clk for window - (now - t_start);
        if rising_edge(o_clk) then
          n_edges := n_edges + 1;
        end if;
      end loop;
      expected := window / src_period;
      check(abs(n_edges - expected) <= 2,
            "expected ~" & integer'image(expected) &
            " edges of " & src_label & " over window, got " &
            integer'image(n_edges));
    end procedure;

    -- Toggle sel several times and observe min edge-to-edge interval and
    -- max edge count over a 5-A-period window.
    procedure stress_and_observe(min_interval : out time;
                                 max_edges_5a : out integer) is
      variable v_min      : time := 1 sec;
      variable v_max      : integer := 0;
      variable v_eds      : integer;
      variable v_window   : time;
      variable v_t_start  : time;
      variable v_last_edg : time;
    begin
      v_last_edg := now;
      for i in 0 to 7 loop
        sel <= not sel;
        v_t_start := now;
        v_window  := 5 * C_PER_A;
        v_eds     := 0;
        while now - v_t_start < v_window loop
          wait on o_clk for v_window - (now - v_t_start);
          if o_clk'event then
            if (now - v_last_edg) > 0 ns and (now - v_last_edg) < v_min then
              v_min := now - v_last_edg;
            end if;
            v_last_edg := now;
            v_eds := v_eds + 1;
          end if;
        end loop;
        if v_eds > v_max then
          v_max := v_eds;
        end if;
      end loop;
      min_interval := v_min;
      max_edges_5a := v_max;
    end procedure;

    variable v_min : time;
    variable v_max : integer;

  begin
    test_runner_setup(runner, runner_cfg);

    while test_suite loop

      sel <= '0';
      wait for 10 * C_PER_A;  -- settle handshake

      if run("default_select_a") then
        check_freq(C_PER_A, "clk_a (13.5 MHz)", 10 * C_PER_A);

      elsif run("default_select_b") then
        sel <= '1';
        wait for 10 * C_PER_A;
        check_freq(C_PER_B, "clk_b (27 MHz)", 10 * C_PER_B);

      elsif run("switch_a_to_b") then
        check_freq(C_PER_A, "clk_a (13.5 MHz)", 5 * C_PER_A);
        sel <= '1';
        wait for 8 * C_PER_A;
        check_freq(C_PER_B, "clk_b (27 MHz)", 10 * C_PER_B);

      elsif run("switch_b_to_a") then
        sel <= '1';
        wait for 8 * C_PER_A;
        check_freq(C_PER_B, "clk_b (27 MHz)", 5 * C_PER_B);
        sel <= '0';
        wait for 8 * C_PER_A;
        check_freq(C_PER_A, "clk_a (13.5 MHz)", 10 * C_PER_A);

      elsif run("no_short_intervals") then
        stress_and_observe(v_min, v_max);
        check(v_min >= C_PER_B / 2 - 1 ns,
              "shortest o_clk interval " & time'image(v_min) &
              " is below faster source half-period " &
              time'image(C_PER_B / 2));

      elsif run("no_double_speed") then
        stress_and_observe(v_min, v_max);
        -- Faster source (27 MHz) over 5 * C_PER_A = 5 * 74.074 ns = 370.37 ns
        -- gives 5 * 2 = 10 rising edges, 20 transitions.  Allow some slack
        -- for measurement-window granularity but reject runaway oscillation.
        check(v_max <= 25,
              "max o_clk transitions per 5*C_PER_A window was " &
              integer'image(v_max) &
              " (expected <= 25)");

      end if;
    end loop;

    stop <= '1';
    test_runner_cleanup(runner);
    wait;
  end process;

end architecture tb;
